version: 2.1

commands:
  say-hello:
    parameters:
      to:
        type: string
        default: ${CIRCLE_USERNAME}
    steps:
      - run: echo "Hello << parameters.to >>"

executors:
  default:
    parameters:
      tag:
        default: latest
        type: string
    docker:
      - image: bash:<< parameters.tag >>

jobs:
  hello-build:
    executor:
      name: default
      tag: "4"
    steps:
      - say-hello:
        to: "Circle"
      - say-hello:
        to: "CI"

workflows:
  workflow:
    jobs:
      - hello-build
